AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/InlineComment:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

StringLiterals:
  EnforcedStyle: double_quotes

DotPosition:
  EnforcedStyle: leading
